import Head from 'next/head'
import {gql, useQuery} from '@apollo/client'

const message = gql`
    query {
        categories {
            name,
            id
        }
    }
`

export default function Home() {
    const {data, loading} = useQuery(message)

    console.log(loading, data)

    return (
        <div>
            <Head>
                <title>Blog</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main>
                <div>{!loading && data.categories.map(it => it.name).join(',')}</div>
            </main>
        </div>
    )
}
